version: 2

jobs:
  test:
    docker:
      - image: circleci/node:6.10-browsers
      - image: mongo:3.2.13

    steps:
      - checkout
      - run: git submodule update --init

      - run:
          name: set-locale
          command: sudo apt-get install locales

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: install-meteor
          command: sh scripts/install-meteor.sh

#      - run:
#          name: install-bcrypt
#          command: meteor npm install --save bcrypt

      - run:
          name: install-chimp
          command: sudo npm install -g chimp

      - run:
          name: install-selenium
          command: sudo npm install -g selenium-standalone

      - run:
          name: install-chimp-dependencies
          command: sh scripts/download-chimp-dependencies.sh

      - run:
          name: install-npm-dependencies
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
            - ~/.npm
            - ~/.meteor

      - run:
          name: meteor-unit-tests
          command: npm run test:unit

      - run:
          name: start-meteor-app
          command: npm run start-ci
          background: true

      - run:
          name: wait-for-app
          command: sleep 50

      - run:
          name: int-test-designs
          command: npm run chimp:int_server_des

      - run:
          name: int-test-wps
          command: npm run chimp:int_server_wp

      - run:
          name: int-test-dev
          command: npm run chimp:int_server_dev

      - run:
          name: int-test-summary
          command: npm run chimp:int_server_sum

      - run:
          name: int-test-design-updates
          command: npm run chimp:int_server_du

      - run:
          name: int-test-domain
          command: npm run chimp:int_server_dom

      - run:
          name: int-test-admin
          command: npm run chimp:int_server_adm

      - run:
          name: client-tests
          command: npm run chimp:int_client

      - run:
          name: upload-results - unit
          command: sh scripts/upload-test-results.sh unit_results.json

      - run:
          name: upload-results - integration designs
          command: sh scripts/upload-test-results.sh mocha_int_results_server_des.json

      - run:
          name: upload-results - integration work packages
          command: sh scripts/upload-test-results.sh mocha_int_results_server_wp.json

      - run:
          name: upload-results - integration development
          command: sh scripts/upload-test-results.sh mocha_int_results_server_dev.json

      - run:
          name: upload-results - integration summaries
          command: sh scripts/upload-test-results.sh mocha_int_results_server_sum.json

      - run:
          name: upload-results - integration design updates
          command: sh scripts/upload-test-results.sh mocha_int_results_server_du.json

      - run:
          name: upload-results - integration domain
          command: sh scripts/upload-test-results.sh mocha_int_results_server_dom.json

      - run:
          name: upload-results - integration admin
          command: sh scripts/upload-test-results.sh mocha_int_results_server_adm.json

      - run:
          name: upload-results - integration client
          command: sh scripts/upload-test-results.sh mocha_int_results_client.json

workflows:
  version: 2
  build_test_upload:
    jobs:
      - test
