

export const AddActionIds = {
    UI_CONTEXT_ADD_DESIGN:              'ADD_DESIGN',
    UI_CONTEXT_ADD_DESIGN_UPDATE:       'ADD_DESIGN_UPDATE',
    UI_CONTEXT_ADD_WORK_PACKAGE:        'ADD_WORK_PACKAGE',
    UI_CONTEXT_ADD_DOMAIN_TERM:         'ADD_DOMAIN_TERM',
    UI_CONTEXT_ADD_USER:                'ADD_USER',
    UI_CONTEXT_ADD_TEST_FILE:           'ADD_TEST_FILE',
    UI_CONTEXT_ADD_TEST_LOCATION:       'ADD_TEST_LOCATION',
    UI_CONTEXT_ADD_APPLICATION:         'ADD_APPLICATION',
    UI_CONTEXT_ADD_DESIGN_SECTION_TO:   'ADD_DESIGN_SECTION_TO_',
    UI_CONTEXT_ADD_FEATURE_TO:          'ADD_FEATURE_TO_',
    UI_CONTEXT_ADD_FEATURE_ASPECT_TO:   'ADD_FEATURE_ASPECT_TO_',
    UI_CONTEXT_ADD_SCENARIO_TO:         'ADD_SCENARIO_TO_'
};