

export const AddActionIds = {
    UI_CONTEXT_ADD_DESIGN:              'ADD_DESIGN',
    UI_CONTEXT_ADD_DESIGN_UPDATE:       'ADD_DESIGN_UPDATE',
    UI_CONTEXT_ADD_WORK_PACKAGE:        'ADD_WORK_PACKAGE',
    UI_CONTEXT_ADD_DOMAIN_TERM:         'ADD_DOMAIN_TERM',
    UI_CONTEXT_ADD_USER:                'ADD_USER',
    UI_CONTEXT_ADD_TEST_FILE:           'ADD_TEST_FILE',
    UI_CONTEXT_ADD_TEST_LOCATION:       'ADD_TEST_LOCATION',
    UI_CONTEXT_ADD_APPLICATION:         'ADD_APPLICATION',
    UI_CONTEXT_ADD_DESIGN_SECTION_TO:   'ADD_DESIGN_SECTION_TO_',
    UI_CONTEXT_ADD_FEATURE_TO:          'ADD_FEATURE_TO_',
    UI_CONTEXT_ADD_FEATURE_ASPECT_TO:   'ADD_FEATURE_ASPECT_TO_',
    UI_CONTEXT_ADD_SCENARIO_TO:         'ADD_SCENARIO_TO_'
};

export const UITab = {
    TAB_DETAILS:                    'tab-details',
    TAB_DOMAIN_DICT:                'tab-dict',
    TAB_ACC_TESTS:                  'tab-acc',
    TAB_INT_TESTS:                  'tab-int',
    TAB_UNIT_TESTS:                 'tab-unit',
    TAB_SCENARIO_SEARCH:            'tab-search',
    TAB_UPDATE_SUMMARY:             'tab-update-summary',
    TAB_WORKING_VIEW:               'tab-working-view'
};

export const UI = {

    BUTTON_REMOVE:                      'but-remove-',
    BUTTON_EDIT:                        'but-edit-',
    BUTTON_VIEW:                        'but-view-',
    BUTTON_ARCHIVE:                     'but-archive-',
    BUTTON_BACKUP:                      'but-backup-',
    BUTTON_RESTORE:                     'but-restore',
    BUTTON_PUBLISH:                     'but-publish',
    BUTTON_WITHDRAW:                    'but-withdraw',
    BUTTON_ADOPT:                       'but-adopt-',
    BUTTON_RELEASE:                     'but-release-',
    BUTTON_DEVELOP:                     'but-develop-',
    BUTTON_CREATE_NEXT:                 'but-create-next-',
    BUTTON_CHANGE_PASSWORD:             'but-change-password',
    EDITABLE_FIELD:                     'edit-field-view-',
    EDITABLE_FIELD_EDITING:             'edit-field-edit-',
    READ_ONLY_FIELD:                    'read-only-field-',
    ITEM_SUMMARY:                       'item-summary-',
    ITEM_MERGE_OPTIONS:                 'item-merge-options-',
    MERGE_OPTION_INCLUDE:               'merge-include-',
    MERGE_OPTION_ROLL:                  'merge-roll-',
    MERGE_OPTION_IGNORE:                'merge-ignore-',
    ITEM_DESIGN:                        'd-',
    ITEM_DESIGN_VERSION:                'dv-',
    ITEM_DESIGN_UPDATE:                 'du-',
    ITEM_WORK_PACKAGE:                  'wp-',
    OPTION_EDIT:                        'opt-edit-',
    OPTION_SAVE:                        'opt-save-',
    OPTION_UNDO:                        'opt-undo-',
    OPTION_REMOVE:                      'opt-remove-',
    OPTION_MOVE:                        'opt-move-',
    OPTION_RESET:                       'opt-reset-',
    OPTION_TOGGLE_ACTIVE:               'opt-toggle-active-',
    OPTION_MENU_ICON:                   'opt-menu-icon-',
    UW_ITEM_SELECTED:                   'uw-item-selected-',
    UW_ITEM_UNSELECTED:                 'uw-item-unselected-',
    SCOPE_COMPONENT:                    'scope-component-',
    DESIGN_COMPONENT:                   'design-component-',
    WORKING_COMPONENT:                  'working-component-',
    COMPONENT_SELECTED:                 'component-selected-',
    COMPONENT_UNSELECTED:               'component-unselected-',
    LINK_ITEM_LINK_LABEL:               'link-label-',
    CONFIG_PASSWORD:                    'config-password',
    MODAL_NEXT_VERSION:                 'modal-next-dv-',
    MODAL_DV_OK:                        'modal-dv-ok-',
    MODAL_DV_CANCEL:                    'modal-dv-cancel-',
    MODAL_DV_UPDATES_MERGE:             'modal-dv-upd-merge-',
    MODAL_DV_UPDATES_ROLL:              'modal-dv-upd-roll-',
    MODAL_DV_UPDATES_IGNORE:            'modal-dv-upd-ignore-',
    INPUT_SCENARIO_SEARCH:              'input-scenario-search',
    INPUT_USER_NAME:                    'input-user-name-',
    INPUT_DISPLAY_NAME:                 'input-display-name-',
    INPUT_ROLE_DESIGNER:                'input-role-designer-',
    INPUT_ROLE_DEVELOPER:               'input-role-developer-',
    INPUT_ROLE_MANAGER:                 'input-role-manager-',
    INPUT_ROLE_GUEST:                   'input-role-guest-',
    INPUT_PASSWORD_OLD:                 'input-password-old',
    INPUT_PASSWORD_NEW1:                'input-password-new1',
    INPUT_PASSWORD_NEW2:                'input-password-new2',
    OUTPUT_SCENARIO_SEARCH:             'output-scenario-search',
};